.github/workflows/publish.yml
=> build: trigger publish

.changeset/khaki-ducks-rush.md, packages/gboost-ui/src/TransferList.tsx, packages/gboost-ui/src/index.ts
=> feat: add transfer list

.changeset/eight-camels-float.md, packages/gboost-ui/src/Layout/Footer.tsx, packages/gboost-ui/src/Layout/Header.tsx, packages/gboost-ui/src/Layout/Layout.tsx, packages/gboost-ui/src/QueryTable/QueryTable.tsx, packages/gboost-ui/src/QueryTable/TableHeaderCell.tsx, packages/gboost-ui/src/SmartInputs/SmartInputs.tsx, packages/gboost-ui/src/SmartInputs/SmartSelectField.tsx, packages/gboost-ui/src/SmartInputs/SmartTextAreaField.tsx, packages/gboost-ui/src/SmartInputs/SmartTextField.tsx, packages/gboost-ui/src/SmartInputs/SmartTransferList.tsx, packages/gboost-ui/src/SmartInputs/baseProps.ts, packages/gboost-ui/src/TransferList.tsx, packages/gboost-ui/src/index.ts
=> feat: add smart inputs and customization for

.changeset/quiet-eels-retire.md, docs/docs/getting-started/features.md, packages/gboost-ui/src/Layout/Footer.tsx, packages/gboost-ui/src/Layout/Header.tsx, packages/gboost-ui/src/Layout/Layout.tsx, packages/gboost-ui/src/QueryTable/QueryTable.tsx, packages/gboost-ui/src/QueryTable/SelectionHeader.tsx, packages/gboost-ui/src/QueryTable/TableHeaderCell.tsx
=> feat: update Layout and QueryTable

.changeset/heavy-laws-judge.md, .changeset/heavy-laws-judges.md, docs/docs/contributing.md, packages/gboost-common/src/index.ts, packages/gboost-common/src/mergeDeep.ts, packages/gboost-ui/src/Authenticator.tsx, packages/gboost-ui/src/Layout/Header.tsx, packages/gboost-ui/src/Layout/Layout.tsx, packages/gboost-ui/src/index.ts, packages/gboost/_templates/repo/create/ui/.eslintrc.cjs.t, packages/gboost/_templates/repo/create/ui/src/App.tsx.t
=> feat: add user prop to Layout; title to totp issuer

.changeset/strong-flowers-crash.md, packages/gboost-ui/src/QueryTable/Pagination.tsx
=> fix: remove console.log from Pagination component

.changeset/angry-cows-leave.md, .changeset/light-dryers-eat.md, .changeset/long-wombats-greet.md, .changeset/selfish-geese-add.md, packages/gboost-ui/src/QueryTable/ActionBar/ActionBar.tsx, packages/gboost-ui/src/QueryTable/ActionBar/FilterAction/FilterRow.tsx, packages/gboost-ui/src/QueryTable/ActionBar/FilterAction/NewFilterRow.tsx, packages/gboost-ui/src/QueryTable/QueryTable.tsx
=> Fix query table

.changeset/honest-parrots-warn.md, packages/gboost/src/help.ts, packages/gboost/src/index.ts, packages/gboost/src/run-fn/setup-fn.ts
=> feat(gboost): Add ability to debug run-fn

.changeset/gentle-dolphins-notice.md, .changeset/rude-boxes-film.md, .changeset/seven-emus-hang.md, packages/gboost-infra/src/function.ts, packages/gboost-ui/src/Layout/Header/Header.tsx, packages/gboost-ui/src/Layout/Layout.tsx, packages/gboost-ui/src/SmartFields/SmartDateTimeField.tsx
=> Feat misc updates

.changeset/empty-ghosts-deny.md, .vscode/settings.json, packages/gboost-ui/src/components/Dialog.tsx
=> feat: add css prop to Dialog

.changeset/beige-horses-wink.md, .changeset/forty-adults-jam.md, .github/workflows/ci.yml, packages/gboost-ui/src/QueryTable/ActionBar/FilterAction/FilterAction.tsx, packages/gboost-ui/src/QueryTable/QueryTable.tsx, packages/gboost-ui/src/QueryTable/SelectionHeader.tsx, packages/gboost-ui/src/QueryTable/TableHeaderCell.tsx, packages/gboost-ui/src/SmartFields/SmartSelectField.tsx
=> Feat query table

.changeset/empty-buttons-boil.md, .github/workflows/ci.yml, package.json, packages/gboost-ui/src/components/Fields/MultiCheckboxField.tsx, pnpm-lock.yaml
=> fix: multi-checkbox

.changeset/green-students-chew.md, .changeset/polite-phones-smash.md, packages/gboost-infra/package.json, packages/gboost-infra/src/file-upload/function/index.ts, packages/gboost-ui/package.json, packages/gboost-ui/src/Layout/Header/AccountMenu.tsx, packages/gboost-ui/src/Layout/Header/Header.tsx, packages/gboost-ui/src/Layout/Layout.tsx, packages/gboost-ui/src/UserManagement/GroupsTable.tsx, packages/gboost-ui/src/UserManagement/UsersInGroupTable.tsx, packages/gboost-ui/src/UserManagement/UsersTable.tsx, packages/gboost-ui/src/UserManagement/common.tsx, packages/gboost-ui/src/components/Fields/MultiCheckboxField.tsx, pnpm-lock.yaml
=> fix: MultiCheckboxField

.changeset/brown-dolphins-prove.md, packages/gboost-ui/package.json, packages/gboost-ui/src/SmartFields/SmartTextField.tsx, packages/gboost-ui/src/components/Fields/DateTimeField.tsx, packages/gboost-ui/src/components/Fields/FileUploadField.tsx, pnpm-lock.yaml
=> fix: text fields props types

.changeset/quiet-buckets-argue.md
=> fix: changeset

.changeset/quiet-buckets-argue.md
=> fix: trigger changeset

.changeset/fresh-cups-hammer.md, packages/gboost/tsconfig.build.json
=> fix: gboost cli

.changeset/eighty-days-swim.md, .changeset/tiny-snails-sneeze.md, packages/gboost-infra/src/bucket/bucket.ts, packages/gboost/templates/crud-core/infra/package.json.t, packages/gboost/templates/crud-core/infra/src/config/stage-config.ts, packages/gboost/templates/crud-dynamo/infra/src/config/stage-config.ts, packages/gboost/templates/crud-postgres/infra/src/app/stateful/data.ts, packages/gboost/templates/crud-postgres/infra/src/app/stateful/init-db-custom-resource.ts, packages/gboost/templates/minimal/infra/package.json.t, packages/gboost/templates/minimal/infra/src/config/stage-config.ts
=> Fix aurora pg template

.changeset/bright-ears-hammer.md, .changeset/rich-rats-grab.md, .github/actions/install/action.yml, packages/gboost-infra/package.json, packages/gboost-ui/package.json, packages/gboost-ui/src/QueryTable/ActionBar/FilterAction/FilterRow.tsx, packages/gboost-ui/src/QueryTable/ActionBar/FilterAction/FilterValue.tsx, packages/gboost-ui/src/QueryTable/ActionBar/FilterAction/NewFilterRow.tsx, pnpm-lock.yaml
=> Fix Query Table and Update Peer Deps

.changeset/five-dancers-work.md, packages/gboost/templates/basic-ui/infra/src/app/stateless/ui-stack.ts, packages/gboost/templates/basic-ui/ui/src/config/client-config.ts, packages/gboost/templates/crud-core/infra/package.json.t, packages/gboost/templates/crud-core/ui/package.json.t, packages/gboost/templates/crud-core/ui/src/config/client-config.ts, packages/gboost/templates/crud-postgres/infra/src/app/stateless/ui-stack.ts
Fixes #207 #227
Retain Lambda@Edge for faster deletion of stack and remove CloudFront logging bucket which won't delete sometimes
=> feat: delete stacks faster

.changeset/brave-cougars-occur.md, .changeset/fast-dots-tease.md, docs/src/pages/learn/m3-infra.mdx, docs/src/theme.config.tsx, packages/gboost/templates/crud-core/ui/package.json.t, packages/gboost/templates/crud-postgres/infra/src/app/stateful/db-migration-custom-resource.ts, packages/gboost/templates/crud-postgres/infra/src/app/stateless/ui-stack.ts, packages/gboost/templates/minimal/packages/eslint-config-next/.eslintrc.cjs.t, packages/gboost/templates/minimal/packages/eslint-config-next/package.json.t, packages/gboost/templates/minimal/packages/eslint-config-node/.eslintrc.cjs.t, packages/gboost/templates/minimal/packages/eslint-config-node/package.json.t, packages/gboost/templates/minimal/ui/package.json.t
=> Fix template windows

.changeset/gorgeous-steaks-share.md, .changeset/hungry-falcons-obey.md, .changeset/silver-dragons-obey.md, docs/src/pages/overview/prereqs.mdx, packages/gboost-infra/src/function.ts, packages/gboost-infra/src/web-deployment/web-deployment.ts, packages/gboost/templates/basic-ui/infra/src/app/stateless/ui-stack.ts, packages/gboost/templates/basic-ui/ui/src/components/layout/AppLayout.tsx, packages/gboost/templates/basic-ui/ui/src/components/layout/Drawer.tsx, packages/gboost/templates/crud-postgres/.envrc, packages/gboost/templates/crud-postgres/core/src/config/server-config.ts, packages/gboost/templates/crud-postgres/infra/src/app/stateless/ui-stack.ts
- Fix prettier formatting issues
- Fix sql id compat issue
- Fix --enable-source-maps
=> Misc fixes

packages/gboost/templates/crud-core/ui/src/components/layout/Drawer.tsx
=> fix: ui template code formatting
